name: CICD for Nodejs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_REPO: mohamedouf501/nodejs
    steps:
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        env:
          IMAGE_TAG: ${{ steps.slug.outputs.sha7 }}
        with:
          context: .
          push: true
          tags: $DOCKERHUB_REPO:$IMAGE_TAG

# ##################################################################

      # - name: Dockerhub Login
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      #   run: |
      #     docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      # - name: Build Docker Image
      #   
      #   run: |
      #     docker build . -t $DOCKERHUB_REPO

      # - name: Push Docker Image
      #   run: |
      #     docker push $DOCKERHUB_REPO

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: SSH deploy
        env:
          IMAGE_TAG: ${{ steps.slug.outputs.sha7 }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{secrets.USER_NAME}}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker stop nodeExpress || true
            docker rm nodeExpress || true
            docker pull $DOCKERHUB_REPO
            docker run -d --name nodeExpress -p ${{ secrets.PORT }}:3000 $DOCKERHUB_REPO
