name: CICD for Node.js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_REPO: mohamedouf501/nodejs

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:${{ github.sha }} 

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Extract short SHA
        run: echo "SHA=$(github.sha)" >> $GITHUB_ENV
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker stop nodeExpress || echo NO Container Running
            docker rm nodeExpress || echo NO Container Running
            docker pull ${{ env.DOCKERHUB_REPO }}:${{ env.SHA }} 
            docker run -d --name nodeExpress -p ${{ secrets.PORT }}:3000 ${{ env.DOCKERHUB_REPO }}:${{ env.SHA }} 
