name: CICD for Node.js
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_REPO}}:${{ github.sha }} 

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker stop nodeExpress || echo  No such container: nodeExpress
            docker rm nodeExpress || echo  No such container: nodeExpress 
            docker pull ${{secrets.DOCKER_REPO}}:${{ github.sha }}  
            docker run -d --name nodeExpress -p ${{ secrets.PORT }}:${{ secrets.PORT }} ${{secrets.DOCKER_REPO}}:${{ github.sha  }} 
